### ISSUE TITLE
Raspberry Pi 0 (W) defconfig

### ISSUE THREAD

**Issue by T94T** [Igalia/buildroot-wpe#1]
Hi,
First of all, thanks for your great work! Just now, we are compiling a sample image for the Raspberry Pi 3...
Is there also a defconfig for the Raspberry Pi 0 (W)?

**Comment by mcatanzaro** [comment]
Hi @T94T, we have not tested Raspberry Pi 0.

Actually, we haven't tested Raspberry Pi 2 yet either.

Raspberry Pi 3 is tested and known to be broken. The recipe should build, though.

I'm a bit surprised you found this so quickly. If you can get WPE to run, do let us know. :)

**Comment by T94T** [comment]
We are currently looking for a way to use WPE with a newer buildroot version. That's why we found this so quickly.

> Raspberry Pi 3 is tested and known to be broken.

What do you mean by "broken"? Does it not work on the Raspberry Pi 3?

**Comment by mcatanzaro** [comment]
> What do you mean by "broken"? Does it not work on the Raspberry Pi 3?

Yeah, this is still a WIP effort. We do have a working Yocto recipe, though: https://github.com/Igalia/meta-webkit

**Comment by T94T** [comment]
We are working with buildroot only. Is there another way to have a current buildroot version running with your WPE?

**Comment by mcatanzaro** [comment]
Not currently. Current problem is that weston does not start. You have to manually create and set XDG_RUNTIME_DIR (which shouldn't be necessary) and then once that's done, it just hangs the console when started.

Once we get this working, I'll try to remember to let you know here.

**Comment by T94T** [comment]
Ok, thanks.

**Comment by mcatanzaro** [comment]
I've abandoned this effort as I have no clue how to get it working, and our Yocto image sufficed for our purposes. Sorry. I'll push something to the README to make it really clear that this does not work yet.

**Comment by T94T** [comment]
Thanks for coming back. We are now going to try it with the WebPlatformForEmbedded/buildroot

**Comment by mcatanzaro** [comment]
Be aware that WebPlatformForEmbedded is a **very** different project from upstream WPE. (This buildroot-wpe was an attempt to get upstream WPE working in a buildroot environment.)

**Comment by T94T** [comment]
I appreciate you taking the time to write us back. Could you please give us some ideas what the main difference of the two versions is?

**Comment by mcatanzaro** [comment]
I don't know, sorry. I would ask the WebPlatformForEmbedded developers.
